### ISSUE TITLE
Refurbish produces segfaulting binary

### ISSUE THREAD

**Issue by ntc2** [GaloisInc/renovate#10]
A few test cases in the SFE Embrittle test suite have been failing for awhile, and it seems Renovate is to blame here. Here's a session showing how `refurbish` produces a segfaulting binary when applied to `tests/binaries/linked-list.noopt.nostdlib.x86_64.exe`, but not when applied to `tests/binaries/linked-list.noopt.stdlib.x86_64.exe`:

```
stack exec -- refurbish -o tmp/ll.noopt.nostdlib.refurbish tests/binaries/linked-list.noopt.nostdlib.x86_64.exe

stack exec -- refurbish -o tmp/ll.noopt.stdlib.refurbish tests/binaries/linked-list.noopt.stdlib.x86_64.exe

tests/binaries/linked-list.noopt.stdlib.x86_64.exe 

chmod +x tmp/ll.noopt.stdlib.refurbish && tmp/ll.noopt.stdlib.refurbish

tests/binaries/linked-list.noopt.nostdlib.x86_64.exe             

chmod +x tmp/ll.noopt.nostdlib.refurbish && tmp/ll.noopt.nostdlib.refurbish
zsh: segmentation fault  tmp/ll.noopt.nostdlib.refurbish
```

The `nostdlib` variant defines its own `_start`, but we have other tests that do this which `refurbish` and `embrittle` handle just fine.

Permalink to SFE tests dir with artifacts used for above example: https://github.com/GaloisInc/sfe/tree/22eddcc9e98719d177ea84c0ea6500db7ff29631/tests/binaries .

NOTE: I have not tested this on Renovate `HEAD`, but it's been going on for at least two weeks and I'm testing on a Renovate commit that's 4 days old.

**Comment by travitch** [comment]
I believe that it is due to #6 - that binary has a .bss but no .data section.  The ELF rewriting logic doesn't currently account for that properly, unfortunately.
