### ISSUE TITLE
Add function-level re-use

### ISSUE THREAD

**Issue by travitch** [GaloisInc/renovate#8]
Right now, the rewriter lays out each basic block individually (unless the loop body locality optimization is enabled).  This has a negative impact on performance in critical code, and also fragments the code space, making it harder to re-use space in the original text section by requiring more redirecting jumps (one for each block). We could recover a significant amount of space by redirecting execution at the start of a block, rather than at each basic block.  Additionally, it would be faster, especially if we keep the same block layout within each function as the compiler generated.

**Comment by dmwit** [comment]
c46cd0c519670c66fb3c254247b8459d6d0bd9df finishes this off, I believe.
